SET(SOURCES ui_Screen1.c
    ui_Screen2.c
    ui.c
    ui_comp_hook.c
    ui_helpers.c
    ui_events.c
    ui_img_1417965892.c
    ui_img_1040054024.c
    ui_img_1053183376.c
    ui_img_19026177.c
    fonts/ui_font_COUNTER.c
    fonts/ui_font_HUGE.c
    fonts/ui_font_large.c
    fonts/ui_font_small.c)

add_library(ui ${SOURCES})
