// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
void ui_event_Roller1(lv_event_t * e);
extern lv_obj_t * ui_Roller1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_volumeLBL;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_timeLBL;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_songName;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel10;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1417965892);    // assets\Steve-Zondicons-Play.48.png
LV_IMG_DECLARE(ui_img_1040054024);    // assets\Pictogrammers-Material-Pause.48.png
LV_IMG_DECLARE(ui_img_1053183376);    // assets\Steve-Zondicons-Forward-Step.48.png
LV_IMG_DECLARE(ui_img_19026177);    // assets\Steve-Zondicons-Forward-Step.32.png

LV_FONT_DECLARE(ui_font_COUNTER);
LV_FONT_DECLARE(ui_font_HUGE);
LV_FONT_DECLARE(ui_font_large);
LV_FONT_DECLARE(ui_font_small);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
